services:
  - type: web
    name: fyp-web-app
    env: python
    plan: free
    buildCommand: pip install -r "FYP-25-S1-09 Mongodb Voice Generate/requirements.txt"
    startCommand: python "FYP-25-S1-09 Mongodb Voice Generate/main.py"
    rootDir: .
